- name: Configure EC2 with NGINX and deploy Node.js app
  hosts: all
  become: true
  vars:
    app_src: "../../task1"
    app_dest: "/var/www/nodejs-app"
  tasks:
    - name: Update and install required packages
      yum:
        name:
          - nginx
          - nodejs
        state: present

    - name: Start and enable NGINX
      service:
        name: nginx
        state: started
        enabled: true

    - name: Copy Node.js application files
      copy:
        src: "{{ app_src }}/"
        dest: "{{ app_dest }}/"
        owner: nginx
        group: nginx
        mode: '0755'

    - name: Upload NGINX configuration for Node.js app
      copy:
        src: files/nodejs-app.conf
        dest: /etc/nginx/conf.d/nodejs-app.conf
        owner: root
        group: root
        mode: '0644'

    - name: Remove default NGINX configuration to avoid conflicts
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent

    - name: Test NGINX configuration
      command: nginx -t
      register: nginx_test

    - name: Fail if NGINX configuration test fails
      fail:
        msg: "NGINX configuration test failed"
      when: nginx_test.rc != 0

    - name: Restart NGINX
      service:
        name: nginx
        state: restarted

    - name: Install Node.js dependencies
      shell: |
        cd {{ app_dest }}
        npm install
      args:
        creates: /var/www/nodejs-app/node_modules

    - name: Start Node.js application with PM2 (Process Manager)
      shell: |
        npm install -g pm2
        pm2 start {{ app_dest }}/index.js --name nodejs-app
        pm2 save
        pm2 startup systemd